name: Notes Heartbeat

on:
  schedule:
    - cron: '13 8 * * *'   # runs daily at 08:13 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write heartbeat
        run: |
          mkdir -p .heartbeat
          date -u +"%Y-%m-%dT%H:%M:%SZ" > ".heartbeat/beat-$(date -u +'%Y%m%d').txt"
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .heartbeat/
          git commit -m "chore: heartbeat $(date -u +'%Y-%m-%d')" || echo "no changes"
          git push
